# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1017, 673)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgb(250,0,0);\n"
"    background-color: rgb(255, 106, 0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0,178,178);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_7.addWidget(self.pushButton, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_2.addWidget(self.frame_3, 0, QtCore.Qt.AlignRight)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_33 = QtWidgets.QFrame(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.frame_33.sizePolicy().hasHeightForWidth())
        self.frame_33.setSizePolicy(sizePolicy)
        self.frame_33.setMinimumSize(QtCore.QSize(200, 300))
        self.frame_33.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_33.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_33)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_51 = QtWidgets.QFrame(self.frame_33)
        self.frame_51.setMinimumSize(QtCore.QSize(170, 40))
        self.frame_51.setMaximumSize(QtCore.QSize(170, 40))
        self.frame_51.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_51.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_51.setObjectName("frame_51")
        self.Dashboard_Btn = QtWidgets.QPushButton(self.frame_51)
        self.Dashboard_Btn.setGeometry(QtCore.QRect(0, 0, 170, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Dashboard_Btn.sizePolicy().hasHeightForWidth())
        self.Dashboard_Btn.setSizePolicy(sizePolicy)
        self.Dashboard_Btn.setMinimumSize(QtCore.QSize(170, 40))
        self.Dashboard_Btn.setMaximumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Dashboard_Btn.setFont(font)
        self.Dashboard_Btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Dashboard_Btn.setStyleSheet("/* STYLESHEET FOR PUSH BUTTON: START, SAVE, CLOSE, RESTORE, CONNECT, EDIT */\n"
" QPushButton {\n"
" border: 2px solid rgb(51,51,51);\n"
" border-radius: 5px; \n"
"color:rgb(255,255,255);\n"
" background-color: rgb(51,51,51);\n"
" }\n"
" QPushButton:hover {\n"
" border: 2px solid rgb(0,143,150);\n"
" background-color: rgb(0,143,150);\n"
" }\n"
" QPushButton:pressed {   \n"
"border: 2px solid rgb(0,143,150);\n"
" background-color: rgb(51,51,51);\n"
" }\n"
" QPushButton:disabled {  \n"
"border-radius: 5px; \n"
"border: 2px solid rgb(112,112,112);\n"
" background-color: rgb(112,112,112);\n"
" }\n"
" /* SEE THE EFFECT BELOW*/")
        self.Dashboard_Btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../trial2/Iconstica_v1.0.0-Free_Package/svg/filled/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Dashboard_Btn.setIcon(icon)
        self.Dashboard_Btn.setIconSize(QtCore.QSize(28, 28))
        self.Dashboard_Btn.setCheckable(True)
        self.Dashboard_Btn.setObjectName("Dashboard_Btn")
        self.verticalLayout_8.addWidget(self.frame_51)
        self.studentsFrame_6 = QtWidgets.QFrame(self.frame_33)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.studentsFrame_6.sizePolicy().hasHeightForWidth())
        self.studentsFrame_6.setSizePolicy(sizePolicy)
        self.studentsFrame_6.setMinimumSize(QtCore.QSize(170, 40))
        self.studentsFrame_6.setMaximumSize(QtCore.QSize(200, 40))
        self.studentsFrame_6.setStyleSheet("border: none;\n"
"\n"
"border-top-right-radius:7px;\n"
"border-bottom-right-radius:7px;")
        self.studentsFrame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.studentsFrame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.studentsFrame_6.setObjectName("studentsFrame_6")
        self.Students_Btn = QtWidgets.QPushButton(self.studentsFrame_6)
        self.Students_Btn.setGeometry(QtCore.QRect(0, 0, 171, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Students_Btn.sizePolicy().hasHeightForWidth())
        self.Students_Btn.setSizePolicy(sizePolicy)
        self.Students_Btn.setMinimumSize(QtCore.QSize(160, 40))
        self.Students_Btn.setMaximumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Students_Btn.setFont(font)
        self.Students_Btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Students_Btn.setStyleSheet("/* STYLESHEET FOR PUSH BUTTON: START, SAVE, CLOSE, RESTORE, CONNECT, EDIT */\n"
" QPushButton {\n"
" border: 2px solid rgb(51,51,51);\n"
" border-radius: 5px; \n"
"color:rgb(255,255,255);\n"
" background-color: rgb(51,51,51);\n"
" }\n"
" QPushButton:hover {\n"
" border: 2px solid rgb(0,143,150);\n"
" background-color: rgb(0,143,150);\n"
" }\n"
" QPushButton:pressed {   \n"
"border: 2px solid rgb(0,143,150);\n"
" background-color: rgb(51,51,51);\n"
" }\n"
" QPushButton:disabled {  \n"
"border-radius: 5px; \n"
"border: 2px solid rgb(112,112,112);\n"
" background-color: rgb(112,112,112);\n"
" }\n"
" /* SEE THE EFFECT BELOW*/")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../trial2/Iconstica_v1.0.0-Free_Package/svg/filled/user.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Students_Btn.setIcon(icon1)
        self.Students_Btn.setIconSize(QtCore.QSize(28, 28))
        self.Students_Btn.setCheckable(True)
        self.Students_Btn.setObjectName("Students_Btn")
        self.verticalLayout_8.addWidget(self.studentsFrame_6)
        self.staffFrame_6 = QtWidgets.QFrame(self.frame_33)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.staffFrame_6.sizePolicy().hasHeightForWidth())
        self.staffFrame_6.setSizePolicy(sizePolicy)
        self.staffFrame_6.setMinimumSize(QtCore.QSize(170, 40))
        self.staffFrame_6.setMaximumSize(QtCore.QSize(200, 40))
        self.staffFrame_6.setStyleSheet("border: none;\n"
"\n"
"border-top-right-radius:7px;\n"
"border-bottom-right-radius:7px;")
        self.staffFrame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.staffFrame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.staffFrame_6.setObjectName("staffFrame_6")
        self.Staff_Btn = QtWidgets.QPushButton(self.staffFrame_6)
        self.Staff_Btn.setGeometry(QtCore.QRect(0, 0, 171, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Staff_Btn.sizePolicy().hasHeightForWidth())
        self.Staff_Btn.setSizePolicy(sizePolicy)
        self.Staff_Btn.setMinimumSize(QtCore.QSize(0, 40))
        self.Staff_Btn.setMaximumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Staff_Btn.setFont(font)
        self.Staff_Btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Staff_Btn.setStyleSheet("/* STYLESHEET FOR PUSH BUTTON: START, SAVE, CLOSE, RESTORE, CONNECT, EDIT */\n"
" QPushButton {\n"
" border: 2px solid rgb(51,51,51);\n"
" border-radius: 5px; \n"
"color:rgb(255,255,255);\n"
" background-color: rgb(51,51,51);\n"
" }\n"
" QPushButton:hover {\n"
" border: 2px solid rgb(0,143,150);\n"
" background-color: rgb(0,143,150);\n"
" }\n"
" QPushButton:pressed {   \n"
"border: 2px solid rgb(0,143,150);\n"
" background-color: rgb(51,51,51);\n"
" }\n"
" QPushButton:disabled {  \n"
"border-radius: 5px; \n"
"border: 2px solid rgb(112,112,112);\n"
" background-color: rgb(112,112,112);\n"
" }\n"
" /* SEE THE EFFECT BELOW*/")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../trial2/Iconstica_v1.0.0-Free_Package/svg/filled/multi-user.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Staff_Btn.setIcon(icon2)
        self.Staff_Btn.setIconSize(QtCore.QSize(32, 32))
        self.Staff_Btn.setCheckable(True)
        self.Staff_Btn.setObjectName("Staff_Btn")
        self.verticalLayout_8.addWidget(self.staffFrame_6)
        self.frame_11 = QtWidgets.QFrame(self.frame_33)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setMinimumSize(QtCore.QSize(170, 40))
        self.frame_11.setMaximumSize(QtCore.QSize(200, 40))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.Class_Btn = QtWidgets.QPushButton(self.frame_11)
        self.Class_Btn.setGeometry(QtCore.QRect(0, 0, 170, 40))
        self.Class_Btn.setMinimumSize(QtCore.QSize(0, 40))
        self.Class_Btn.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("Lato Heavy")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Class_Btn.setFont(font)
        self.Class_Btn.setStyleSheet("/* STYLESHEET FOR PUSH BUTTON: START, SAVE, CLOSE, RESTORE, CONNECT, EDIT */\n"
" QPushButton {\n"
" border: 2px solid rgb(51,51,51);\n"
" border-radius: 5px; \n"
"color:rgb(255,255,255);\n"
" background-color: rgb(51,51,51);\n"
" }\n"
" QPushButton:hover {\n"
" border: 2px solid rgb(0,143,150);\n"
" background-color: rgb(0,143,150);\n"
" }\n"
" QPushButton:pressed {   \n"
"border: 2px solid rgb(0,143,150);\n"
" background-color: rgb(51,51,51);\n"
" }\n"
" QPushButton:disabled {  \n"
"border-radius: 5px; \n"
"border: 2px solid rgb(112,112,112);\n"
" background-color: rgb(112,112,112);\n"
" }\n"
" /* SEE THE EFFECT BELOW*/")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../trial2/Iconstica_v1.0.0-Free_Package/svg/filled/graduation-cap.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Class_Btn.setIcon(icon3)
        self.Class_Btn.setObjectName("Class_Btn")
        self.verticalLayout_8.addWidget(self.frame_11)
        self.horizontalLayout_6.addWidget(self.frame_33)
        self.mainBodyTabs = QtWidgets.QStackedWidget(self.frame_6)
        self.mainBodyTabs.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.mainBodyTabs.sizePolicy().hasHeightForWidth())
        self.mainBodyTabs.setSizePolicy(sizePolicy)
        self.mainBodyTabs.setMinimumSize(QtCore.QSize(0, 0))
        self.mainBodyTabs.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mainBodyTabs.setStyleSheet("border-color: rgb(91,90,90);\n"
"background:rgb(91,90,90);\n"
"selection-color: rgb(0, 0, 0);")
        self.mainBodyTabs.setObjectName("mainBodyTabs")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.page_4)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.frame_2)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_9 = QtWidgets.QLabel(self.frame_9)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 59, 15))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_9)
        self.label_10.setGeometry(QtCore.QRect(20, 40, 91, 16))
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.frame_9, 2, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 59, 15))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setGeometry(QtCore.QRect(20, 40, 91, 16))
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.frame_5, 2, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 59, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(20, 40, 91, 16))
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.frame_4, 3, 0, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.frame_2)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_7 = QtWidgets.QLabel(self.frame_10)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 59, 15))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_10)
        self.label_8.setGeometry(QtCore.QRect(20, 40, 131, 16))
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.frame_10, 3, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.mainBodyTabs.addWidget(self.page_4)
        self.page_staff = QtWidgets.QWidget()
        self.page_staff.setObjectName("page_staff")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.page_staff)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_staff = QtWidgets.QFrame(self.page_staff)
        self.frame_staff.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_staff.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_staff.setObjectName("frame_staff")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_staff)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Prof_Tab = QtWidgets.QTabWidget(self.frame_staff)
        self.Prof_Tab.setObjectName("Prof_Tab")
        self.Add_Prof_Tab = QtWidgets.QWidget()
        self.Add_Prof_Tab.setObjectName("Add_Prof_Tab")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.Add_Prof_Tab)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_25 = QtWidgets.QFrame(self.Add_Prof_Tab)
        self.frame_25.setStyleSheet(" border: 2px solid transparent; /* Set border color to transparent */")
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.Prof_LName_LineEdit = QtWidgets.QLineEdit(self.frame_25)
        self.Prof_LName_LineEdit.setMinimumSize(QtCore.QSize(0, 26))
        self.Prof_LName_LineEdit.setStyleSheet(" border: 1px solid rgb(191, 191, 191);; /* Set border color to transparent */\n"
"\n"
"background-color: rgb(229, 229, 229);\n"
" border-radius: 7px;")
        self.Prof_LName_LineEdit.setObjectName("Prof_LName_LineEdit")
        self.verticalLayout_13.addWidget(self.Prof_LName_LineEdit)
        self.gridLayout_4.addWidget(self.frame_25, 0, 3, 1, 1)
        self.frame_26 = QtWidgets.QFrame(self.Add_Prof_Tab)
        self.frame_26.setStyleSheet(" border: 2px solid transparent; /* Set border color to transparent */")
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_20 = QtWidgets.QLabel(self.frame_26)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_15.addWidget(self.label_20)
        self.Prof_Mobile_LineEdit = QtWidgets.QLineEdit(self.frame_26)
        self.Prof_Mobile_LineEdit.setMinimumSize(QtCore.QSize(0, 26))
        self.Prof_Mobile_LineEdit.setStyleSheet(" border: 1px solid rgb(191, 191, 191);; /* Set border color to transparent */\n"
"\n"
"background-color: rgb(229, 229, 229);\n"
" border-radius: 7px;")
        self.Prof_Mobile_LineEdit.setObjectName("Prof_Mobile_LineEdit")
        self.horizontalLayout_15.addWidget(self.Prof_Mobile_LineEdit)
        self.gridLayout_4.addWidget(self.frame_26, 1, 2, 1, 2)
        self.frame_27 = QtWidgets.QFrame(self.Add_Prof_Tab)
        self.frame_27.setStyleSheet(" border: 2px solid transparent; /* Set border color to transparent */")
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_27)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_21 = QtWidgets.QLabel(self.frame_27)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_16.addWidget(self.label_21)
        self.Prof_Title_LineEdit = QtWidgets.QLineEdit(self.frame_27)
        self.Prof_Title_LineEdit.setMinimumSize(QtCore.QSize(0, 26))
        self.Prof_Title_LineEdit.setStyleSheet(" border: 1px solid rgb(191, 191, 191);; /* Set border color to transparent */\n"
"\n"
"background-color: rgb(229, 229, 229);\n"
" border-radius: 7px;")
        self.Prof_Title_LineEdit.setObjectName("Prof_Title_LineEdit")
        self.horizontalLayout_16.addWidget(self.Prof_Title_LineEdit)
        self.gridLayout_4.addWidget(self.frame_27, 3, 2, 1, 1)
        self.frame_28 = QtWidgets.QFrame(self.Add_Prof_Tab)
        self.frame_28.setStyleSheet(" border: 2px solid transparent; /* Set border color to transparent */")
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_28)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_22 = QtWidgets.QLabel(self.frame_28)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_17.addWidget(self.label_22)
        self.Prof_Age_SpinBox = QtWidgets.QSpinBox(self.frame_28)
        self.Prof_Age_SpinBox.setMinimumSize(QtCore.QSize(100, 26))
        self.Prof_Age_SpinBox.setStyleSheet(" border: 1px solid rgb(191, 191, 191);; /* Set border color to transparent */\n"
"\n"
"background-color: rgb(229, 229, 229);")
        self.Prof_Age_SpinBox.setObjectName("Prof_Age_SpinBox")
        self.horizontalLayout_17.addWidget(self.Prof_Age_SpinBox, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_4.addWidget(self.frame_28, 3, 3, 1, 1)
        self.frame_29 = QtWidgets.QFrame(self.Add_Prof_Tab)
        self.frame_29.setStyleSheet(" border: 2px solid transparent; /* Set border color to transparent */")
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_29)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_23 = QtWidgets.QLabel(self.frame_29)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_18.addWidget(self.label_23)
        self.Prof_Email_LineEdit = QtWidgets.QLineEdit(self.frame_29)
        self.Prof_Email_LineEdit.setMinimumSize(QtCore.QSize(0, 26))
        self.Prof_Email_LineEdit.setStyleSheet(" border: 1px solid rgb(191, 191, 191);; /* Set border color to transparent */\n"
"\n"
"background-color: rgb(229, 229, 229);\n"
" border-radius: 7px;")
        self.Prof_Email_LineEdit.setObjectName("Prof_Email_LineEdit")
        self.horizontalLayout_18.addWidget(self.Prof_Email_LineEdit)
        self.gridLayout_4.addWidget(self.frame_29, 2, 2, 1, 2)
        self.prof_name = QtWidgets.QFrame(self.Add_Prof_Tab)
        self.prof_name.setStyleSheet(" border: 2px solid transparent; /* Set border color to transparent */")
        self.prof_name.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.prof_name.setFrameShadow(QtWidgets.QFrame.Raised)
        self.prof_name.setObjectName("prof_name")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.prof_name)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.profName_lab = QtWidgets.QLabel(self.prof_name)
        self.profName_lab.setObjectName("profName_lab")
        self.horizontalLayout.addWidget(self.profName_lab)
        self.Prof_FName_LineEdit = QtWidgets.QLineEdit(self.prof_name)
        self.Prof_FName_LineEdit.setMinimumSize(QtCore.QSize(0, 26))
        self.Prof_FName_LineEdit.setStyleSheet(" border: 1px solid rgb(191, 191, 191);; /* Set border color to transparent */\n"
"\n"
"background-color: rgb(229, 229, 229);\n"
" border-radius: 7px;")
        self.Prof_FName_LineEdit.setObjectName("Prof_FName_LineEdit")
        self.horizontalLayout.addWidget(self.Prof_FName_LineEdit)
        self.gridLayout_4.addWidget(self.prof_name, 0, 2, 1, 1)
        self.verticalLayout_17.addLayout(self.gridLayout_4)
        self.Prof_Add_Btn = QtWidgets.QPushButton(self.Add_Prof_Tab)
        self.Prof_Add_Btn.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(0, 255, 0);\n"
"    border: 2px solid #8f8f91;\n"
"    border-radius: 6px;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #D0D0D0;\n"
"}")
        self.Prof_Add_Btn.setObjectName("Prof_Add_Btn")
        self.verticalLayout_17.addWidget(self.Prof_Add_Btn, 0, QtCore.Qt.AlignHCenter)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../trial2/Iconstica_v1.0.0-Free_Package/svg/filled/plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Prof_Tab.addTab(self.Add_Prof_Tab, icon4, "")
        self.Search_Prof_Tab = QtWidgets.QWidget()
        self.Search_Prof_Tab.setObjectName("Search_Prof_Tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.Search_Prof_Tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.Prof_SearchBar = QtWidgets.QLineEdit(self.Search_Prof_Tab)
        self.Prof_SearchBar.setObjectName("Prof_SearchBar")
        self.gridLayout_6.addWidget(self.Prof_SearchBar, 0, 0, 1, 1)
        self.Prof_Search_Btn = QtWidgets.QPushButton(self.Search_Prof_Tab)
        self.Prof_Search_Btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../.designer/Iconstica_v1.0.0-Free_Package/svg/line/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Prof_Search_Btn.setIcon(icon5)
        self.Prof_Search_Btn.setObjectName("Prof_Search_Btn")
        self.gridLayout_6.addWidget(self.Prof_Search_Btn, 0, 1, 1, 1)
        self.Prof_Search_Result = QtWidgets.QListWidget(self.Search_Prof_Tab)
        self.Prof_Search_Result.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Prof_Search_Result.setObjectName("Prof_Search_Result")
        self.gridLayout_6.addWidget(self.Prof_Search_Result, 1, 0, 1, 2)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../trial2/Iconstica_v1.0.0-Free_Package/svg/filled/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Prof_Tab.addTab(self.Search_Prof_Tab, icon6, "")
        self.verticalLayout_7.addWidget(self.Prof_Tab)
        self.horizontalLayout_5.addWidget(self.frame_staff)
        self.mainBodyTabs.addWidget(self.page_staff)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Class_Search_Bar3_Btn = QtWidgets.QTabWidget(self.page_2)
        self.Class_Search_Bar3_Btn.setObjectName("Class_Search_Bar3_Btn")
        self.Add_Prof_Class_Tab = QtWidgets.QWidget()
        self.Add_Prof_Class_Tab.setObjectName("Add_Prof_Class_Tab")
        self.gridLayout = QtWidgets.QGridLayout(self.Add_Prof_Class_Tab)
        self.gridLayout.setObjectName("gridLayout")
        self.Prof_Search_Bar2 = QtWidgets.QLineEdit(self.Add_Prof_Class_Tab)
        self.Prof_Search_Bar2.setObjectName("Prof_Search_Bar2")
        self.gridLayout.addWidget(self.Prof_Search_Bar2, 0, 0, 1, 1)
        self.Prof_Search_Bar2_Btn = QtWidgets.QPushButton(self.Add_Prof_Class_Tab)
        self.Prof_Search_Bar2_Btn.setText("")
        self.Prof_Search_Bar2_Btn.setIcon(icon5)
        self.Prof_Search_Bar2_Btn.setObjectName("Prof_Search_Bar2_Btn")
        self.gridLayout.addWidget(self.Prof_Search_Bar2_Btn, 0, 1, 1, 1)
        self.Class_Search_Bar2 = QtWidgets.QLineEdit(self.Add_Prof_Class_Tab)
        self.Class_Search_Bar2.setObjectName("Class_Search_Bar2")
        self.gridLayout.addWidget(self.Class_Search_Bar2, 2, 0, 1, 1)
        self.Prof_Search_Result2 = QtWidgets.QListWidget(self.Add_Prof_Class_Tab)
        self.Prof_Search_Result2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Prof_Search_Result2.setObjectName("Prof_Search_Result2")
        self.gridLayout.addWidget(self.Prof_Search_Result2, 1, 0, 1, 2)
        self.Class_Search_Bar2_Btn = QtWidgets.QPushButton(self.Add_Prof_Class_Tab)
        self.Class_Search_Bar2_Btn.setText("")
        self.Class_Search_Bar2_Btn.setIcon(icon5)
        self.Class_Search_Bar2_Btn.setObjectName("Class_Search_Bar2_Btn")
        self.gridLayout.addWidget(self.Class_Search_Bar2_Btn, 2, 1, 1, 1)
        self.Class_Search_Result2 = QtWidgets.QListWidget(self.Add_Prof_Class_Tab)
        self.Class_Search_Result2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Class_Search_Result2.setObjectName("Class_Search_Result2")
        self.gridLayout.addWidget(self.Class_Search_Result2, 3, 0, 1, 2)
        self.Add_Prof_Class_Btn = QtWidgets.QPushButton(self.Add_Prof_Class_Tab)
        self.Add_Prof_Class_Btn.setObjectName("Add_Prof_Class_Btn")
        self.gridLayout.addWidget(self.Add_Prof_Class_Btn, 4, 0, 1, 1)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../trial2/Iconstica_v1.0.0-Free_Package/svg/filled/arrow-right-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Class_Search_Bar3_Btn.addTab(self.Add_Prof_Class_Tab, icon7, "")
        self.Add_Student_Class_Tab = QtWidgets.QWidget()
        self.Add_Student_Class_Tab.setObjectName("Add_Student_Class_Tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Add_Student_Class_Tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Class_Search_Bar3_Btn_2 = QtWidgets.QPushButton(self.Add_Student_Class_Tab)
        self.Class_Search_Bar3_Btn_2.setText("")
        self.Class_Search_Bar3_Btn_2.setIcon(icon5)
        self.Class_Search_Bar3_Btn_2.setObjectName("Class_Search_Bar3_Btn_2")
        self.gridLayout_2.addWidget(self.Class_Search_Bar3_Btn_2, 2, 1, 1, 1)
        self.Class_Search_Result3 = QtWidgets.QListWidget(self.Add_Student_Class_Tab)
        self.Class_Search_Result3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Class_Search_Result3.setObjectName("Class_Search_Result3")
        self.gridLayout_2.addWidget(self.Class_Search_Result3, 3, 0, 1, 2)
        self.Student_Search_Bar2 = QtWidgets.QLineEdit(self.Add_Student_Class_Tab)
        self.Student_Search_Bar2.setObjectName("Student_Search_Bar2")
        self.gridLayout_2.addWidget(self.Student_Search_Bar2, 0, 0, 1, 1)
        self.Student_Search_Bar2_Btn = QtWidgets.QPushButton(self.Add_Student_Class_Tab)
        self.Student_Search_Bar2_Btn.setText("")
        self.Student_Search_Bar2_Btn.setIcon(icon5)
        self.Student_Search_Bar2_Btn.setObjectName("Student_Search_Bar2_Btn")
        self.gridLayout_2.addWidget(self.Student_Search_Bar2_Btn, 0, 1, 1, 1)
        self.Class_Search_Bar3 = QtWidgets.QLineEdit(self.Add_Student_Class_Tab)
        self.Class_Search_Bar3.setObjectName("Class_Search_Bar3")
        self.gridLayout_2.addWidget(self.Class_Search_Bar3, 2, 0, 1, 1)
        self.Student_Search_Result2 = QtWidgets.QListWidget(self.Add_Student_Class_Tab)
        self.Student_Search_Result2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Student_Search_Result2.setObjectName("Student_Search_Result2")
        self.gridLayout_2.addWidget(self.Student_Search_Result2, 1, 0, 1, 2)
        self.Add_Student_Class_Btn = QtWidgets.QPushButton(self.Add_Student_Class_Tab)
        self.Add_Student_Class_Btn.setObjectName("Add_Student_Class_Btn")
        self.gridLayout_2.addWidget(self.Add_Student_Class_Btn, 4, 0, 1, 1)
        self.Class_Search_Bar3_Btn.addTab(self.Add_Student_Class_Tab, icon7, "")
        self.Sarch_Class_Tab = QtWidgets.QWidget()
        self.Sarch_Class_Tab.setObjectName("Sarch_Class_Tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.Sarch_Class_Tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.Class_SearchBar = QtWidgets.QLineEdit(self.Sarch_Class_Tab)
        self.Class_SearchBar.setObjectName("Class_SearchBar")
        self.gridLayout_7.addWidget(self.Class_SearchBar, 0, 0, 1, 1)
        self.Class_SearchBar_Btn = QtWidgets.QPushButton(self.Sarch_Class_Tab)
        self.Class_SearchBar_Btn.setText("")
        self.Class_SearchBar_Btn.setIcon(icon5)
        self.Class_SearchBar_Btn.setObjectName("Class_SearchBar_Btn")
        self.gridLayout_7.addWidget(self.Class_SearchBar_Btn, 0, 1, 1, 1)
        self.Class_Search_Result = QtWidgets.QListWidget(self.Sarch_Class_Tab)
        self.Class_Search_Result.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Class_Search_Result.setObjectName("Class_Search_Result")
        self.gridLayout_7.addWidget(self.Class_Search_Result, 1, 0, 1, 2)
        self.Class_Search_Bar3_Btn.addTab(self.Sarch_Class_Tab, icon6, "")
        self.horizontalLayout_3.addWidget(self.Class_Search_Bar3_Btn)
        self.mainBodyTabs.addWidget(self.page_2)
        self.StudentPage = QtWidgets.QWidget()
        self.StudentPage.setObjectName("StudentPage")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.StudentPage)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_23 = QtWidgets.QFrame(self.StudentPage)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.Student_Tab = QtWidgets.QTabWidget(self.frame_23)
        self.Student_Tab.setStyleSheet("")
        self.Student_Tab.setObjectName("Student_Tab")
        self.Search_Student_Tab = QtWidgets.QWidget()
        self.Search_Student_Tab.setObjectName("Search_Student_Tab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.Search_Student_Tab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.Student_Search_Btn = QtWidgets.QPushButton(self.Search_Student_Tab)
        self.Student_Search_Btn.setText("")
        self.Student_Search_Btn.setIcon(icon5)
        self.Student_Search_Btn.setObjectName("Student_Search_Btn")
        self.gridLayout_9.addWidget(self.Student_Search_Btn, 0, 1, 1, 1)
        self.Student_SearchBar = QtWidgets.QLineEdit(self.Search_Student_Tab)
        self.Student_SearchBar.setObjectName("Student_SearchBar")
        self.gridLayout_9.addWidget(self.Student_SearchBar, 0, 0, 1, 1)
        self.Student_Search_Result = QtWidgets.QListWidget(self.Search_Student_Tab)
        self.Student_Search_Result.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Student_Search_Result.setObjectName("Student_Search_Result")
        self.gridLayout_9.addWidget(self.Student_Search_Result, 1, 0, 1, 2)
        self.Student_Tab.addTab(self.Search_Student_Tab, icon6, "")
        self.Add_Student_Tab = QtWidgets.QWidget()
        self.Add_Student_Tab.setObjectName("Add_Student_Tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Add_Student_Tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.frame_46 = QtWidgets.QFrame(self.Add_Student_Tab)
        self.frame_46.setStyleSheet(" border: 2px solid transparent; /* Set border color to transparent */")
        self.frame_46.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_46.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_46.setObjectName("frame_46")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_46)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_34 = QtWidgets.QLabel(self.frame_46)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_12.addWidget(self.label_34)
        self.Student_FName_LineEdit = QtWidgets.QLineEdit(self.frame_46)
        self.Student_FName_LineEdit.setMinimumSize(QtCore.QSize(0, 26))
        self.Student_FName_LineEdit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(74, 148, 146);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(252, 255, 29);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(255, 0, 0);\n"
"    color: rgb(250, 250, 250);\n"
"}")
        self.Student_FName_LineEdit.setObjectName("Student_FName_LineEdit")
        self.horizontalLayout_12.addWidget(self.Student_FName_LineEdit)
        self.gridLayout_8.addWidget(self.frame_46, 0, 2, 1, 1)
        self.frame_44 = QtWidgets.QFrame(self.Add_Student_Tab)
        self.frame_44.setStyleSheet(" border: 2px solid transparent; /* Set border color to transparent */")
        self.frame_44.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_44.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_44.setObjectName("frame_44")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_44)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_32 = QtWidgets.QLabel(self.frame_44)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_25.addWidget(self.label_32)
        self.Student_Age_SpinBox = QtWidgets.QSpinBox(self.frame_44)
        self.Student_Age_SpinBox.setMinimumSize(QtCore.QSize(100, 26))
        self.Student_Age_SpinBox.setStyleSheet(" border: 1px solid rgb(191, 191, 191);; /* Set border color to transparent */\n"
"\n"
"background-color: rgb(229, 229, 229);")
        self.Student_Age_SpinBox.setObjectName("Student_Age_SpinBox")
        self.horizontalLayout_25.addWidget(self.Student_Age_SpinBox, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_8.addWidget(self.frame_44, 3, 3, 1, 1)
        self.frame_45 = QtWidgets.QFrame(self.Add_Student_Tab)
        self.frame_45.setStyleSheet(" border: 2px solid transparent; /* Set border color to transparent */")
        self.frame_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frame_45)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_33 = QtWidgets.QLabel(self.frame_45)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_26.addWidget(self.label_33)
        self.Student_Email_LineEdit = QtWidgets.QLineEdit(self.frame_45)
        self.Student_Email_LineEdit.setMinimumSize(QtCore.QSize(0, 26))
        self.Student_Email_LineEdit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(74, 148, 146);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(252, 255, 29);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(255, 0, 0);\n"
"    color: rgb(250, 250, 250);\n"
"}")
        self.Student_Email_LineEdit.setObjectName("Student_Email_LineEdit")
        self.horizontalLayout_26.addWidget(self.Student_Email_LineEdit)
        self.gridLayout_8.addWidget(self.frame_45, 2, 2, 1, 2)
        self.frame_43 = QtWidgets.QFrame(self.Add_Student_Tab)
        self.frame_43.setStyleSheet(" border: 2px solid transparent; /* Set border color to transparent */")
        self.frame_43.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_43.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_43.setObjectName("frame_43")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_43)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_31 = QtWidgets.QLabel(self.frame_43)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_24.addWidget(self.label_31)
        self.Student_Grade_LineEdit = QtWidgets.QLineEdit(self.frame_43)
        self.Student_Grade_LineEdit.setMinimumSize(QtCore.QSize(0, 26))
        self.Student_Grade_LineEdit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(74, 148, 146);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(252, 255, 29);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(255, 0, 0);\n"
"    color: rgb(250, 250, 250);\n"
"}")
        self.Student_Grade_LineEdit.setObjectName("Student_Grade_LineEdit")
        self.horizontalLayout_24.addWidget(self.Student_Grade_LineEdit)
        self.gridLayout_8.addWidget(self.frame_43, 3, 2, 1, 1)
        self.frame_41 = QtWidgets.QFrame(self.Add_Student_Tab)
        self.frame_41.setStyleSheet(" border: 2px solid transparent; /* Set border color to transparent */")
        self.frame_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_41)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.Student_LName_LineEdit = QtWidgets.QLineEdit(self.frame_41)
        self.Student_LName_LineEdit.setMinimumSize(QtCore.QSize(0, 26))
        self.Student_LName_LineEdit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(74, 148, 146);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(252, 255, 29);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(255, 0, 0);\n"
"    color: rgb(250, 250, 250);\n"
"}")
        self.Student_LName_LineEdit.setObjectName("Student_LName_LineEdit")
        self.verticalLayout_21.addWidget(self.Student_LName_LineEdit)
        self.gridLayout_8.addWidget(self.frame_41, 0, 3, 1, 1)
        self.frame_42 = QtWidgets.QFrame(self.Add_Student_Tab)
        self.frame_42.setStyleSheet(" border: 2px solid transparent; /* Set border color to transparent */")
        self.frame_42.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_42.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_42.setObjectName("frame_42")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_42)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_30 = QtWidgets.QLabel(self.frame_42)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_23.addWidget(self.label_30)
        self.Student_Mobile_LineEdit = QtWidgets.QLineEdit(self.frame_42)
        self.Student_Mobile_LineEdit.setMinimumSize(QtCore.QSize(0, 26))
        self.Student_Mobile_LineEdit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(74, 148, 146);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);    \n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(252, 255, 29);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(255, 0, 0);\n"
"    color: rgb(250, 250, 250);\n"
"}")
        self.Student_Mobile_LineEdit.setObjectName("Student_Mobile_LineEdit")
        self.horizontalLayout_23.addWidget(self.Student_Mobile_LineEdit)
        self.gridLayout_8.addWidget(self.frame_42, 1, 2, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout_8)
        self.Student_Add_Btn = QtWidgets.QPushButton(self.Add_Student_Tab)
        self.Student_Add_Btn.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}")
        self.Student_Add_Btn.setObjectName("Student_Add_Btn")
        self.verticalLayout.addWidget(self.Student_Add_Btn)
        self.Student_Tab.addTab(self.Add_Student_Tab, icon4, "")
        self.Show_Student_Tab = QtWidgets.QWidget()
        self.Show_Student_Tab.setObjectName("Show_Student_Tab")
        self.Student_Tab.addTab(self.Show_Student_Tab, "")
        self.verticalLayout_16.addWidget(self.Student_Tab)
        self.horizontalLayout_4.addWidget(self.frame_23)
        self.mainBodyTabs.addWidget(self.StudentPage)
        self.horizontalLayout_6.addWidget(self.mainBodyTabs)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.horizontalLayout_2.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1017, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.mainBodyTabs.setCurrentIndex(3)
        self.Prof_Tab.setCurrentIndex(1)
        self.Class_Search_Bar3_Btn.setCurrentIndex(2)
        self.Student_Tab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.Students_Btn.setText(_translate("MainWindow", "Students"))
        self.Staff_Btn.setText(_translate("MainWindow", "Staff"))
        self.Class_Btn.setText(_translate("MainWindow", "Class"))
        self.label_2.setText(_translate("MainWindow", "welcome to your edu-center dashboard"))
        self.label.setText(_translate("MainWindow", "Dashboard"))
        self.label_9.setText(_translate("MainWindow", "analytics"))
        self.label_10.setText(_translate("MainWindow", "total students"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "total clases"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "total students"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "total professors"))
        self.label_20.setText(_translate("MainWindow", "mobile"))
        self.label_21.setText(_translate("MainWindow", "title"))
        self.label_22.setText(_translate("MainWindow", "age"))
        self.label_23.setText(_translate("MainWindow", "email"))
        self.profName_lab.setText(_translate("MainWindow", "name"))
        self.Prof_Add_Btn.setText(_translate("MainWindow", "Add"))
        self.Prof_Tab.setTabText(self.Prof_Tab.indexOf(self.Add_Prof_Tab), _translate("MainWindow", "Add Professor"))
        self.Prof_Tab.setTabText(self.Prof_Tab.indexOf(self.Search_Prof_Tab), _translate("MainWindow", "search"))
        self.Add_Prof_Class_Btn.setText(_translate("MainWindow", "add professor to class"))
        self.Class_Search_Bar3_Btn.setTabText(self.Class_Search_Bar3_Btn.indexOf(self.Add_Prof_Class_Tab), _translate("MainWindow", "Add Professor to Class"))
        self.Add_Student_Class_Btn.setText(_translate("MainWindow", "Add Student to Class"))
        self.Class_Search_Bar3_Btn.setTabText(self.Class_Search_Bar3_Btn.indexOf(self.Add_Student_Class_Tab), _translate("MainWindow", "Add Student to Class"))
        self.Class_Search_Bar3_Btn.setTabText(self.Class_Search_Bar3_Btn.indexOf(self.Sarch_Class_Tab), _translate("MainWindow", "search"))
        self.Student_Tab.setTabText(self.Student_Tab.indexOf(self.Search_Student_Tab), _translate("MainWindow", "search"))
        self.label_34.setText(_translate("MainWindow", "name"))
        self.label_32.setText(_translate("MainWindow", "age"))
        self.label_33.setText(_translate("MainWindow", "email"))
        self.label_31.setText(_translate("MainWindow", "grade"))
        self.label_30.setText(_translate("MainWindow", "mobile"))
        self.Student_Add_Btn.setText(_translate("MainWindow", "Add"))
        self.Student_Tab.setTabText(self.Student_Tab.indexOf(self.Add_Student_Tab), _translate("MainWindow", "Add Student"))
        self.Student_Tab.setTabText(self.Student_Tab.indexOf(self.Show_Student_Tab), _translate("MainWindow", "Show Student"))
import Resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
